### ISSUE TITLE
dosent work on v1.5

### ISSUE THREAD

**Issue by jonibim** [hypoxic/hero4-session#2]
Autoexec dosent work on frimware 1.5

**Comment by francisra** [comment]
I recently upgraded to version   HX1.01.01.50  and  I can confirm that with this firmware version autoexec.ash doesnt work.
Is it possible to downgrade to   HX1.01.01.00?

**Comment by jonibim** [comment]
Yes...if you find a frimware of thag version

**Comment by hypoxic** [comment]
GoPro never released a firmware file for HX1 01.00 as far as we can tell. Recreating one would  be against the EULA. We're exploring some new solutions for 1.50 "HX1.01-firmware.bin"

**Comment by hypoxic** [comment]
The firmware checks for d:\autoexec.ash but never spawns off a task to run it. It may be possible to modify the fw to spawn this task, but its no easy endeavor. What are people using autoexec.ash for? There may be a better solution.

**Comment by jonibim** [comment]
Maybe you can modify the current version frimware with Notepad ++...i opened the bin file (i know that its stupid) with Notepad ++ and found out there to be 4 autoexec.ash words in some lines...maybe by deleting the autoexec.ash words on lines...it might work...by the way hypoxic which is the "better solution"?...overdrive hack?

**Comment by jonibim** [comment]
Look we can work together and find a solution for this problem.

**Comment by hypoxic** [comment]
They are checking for d:\autoexec.ash in the startup of ambsh but never spawn off a new task to run the script. The other autoexec' you are seeing are for ddr testing. Running of scripts work once in the shell, but unfortunately modifying the firmware to spawn off running the script is a daunting task to say the least. We could add a Linux handler but that gives a lot less control. Hence why I'm asking what are you using it for.

**Comment by francisra** [comment]
Hi thanks all for the answers. I would pretend to have working autoxec.ash for the following:

Mounting the usb interface of the camera as a mass storage device.
At the same time, beeing able to control it via wifi. 

If that will be possible, I would be happy...

**Comment by jonibim** [comment]
@francisra, they can't work on v1.50 as autoexec.ash doesn't work on this version.

**Comment by jonibim** [comment]
hypoxic, can you export gopro frimware from the gopro cameras? A better question, Is it possible?

**Comment by hypoxic** [comment]
@djbeat2990 You can export the firmware using the firmfl command but you have to give the correct order to the sections and I honestly would not try this since there is no undo if you do something wrong. Basically a high probability of "bricking" your camera.

**Comment by jonibim** [comment]
but that "bricking" can be fixed by updating the camera?

**Comment by hypoxic** [comment]
@francisra There is another way to make the device MSC vs. MTP. I'll work on that solution. However, you should be able to control the GoPro via MTP, I just haven't worked on that route. You can download files over wifi if you are already controlling it over that interface, not sure if you can do both at the same time.

**Comment by hypoxic** [comment]
@djbeat2990 Not if you screw up the rtos firmware by updating it with a wrong section. Something has to be in control and if you overwrite that with nonsense, you have destroyed your camera.

**Comment by jonibim** [comment]
@hypoxic so there are ways to get autoexec working again but they are too dangareous. :/ this is going to be tough. I asked about the overdrive hack but the "creator of this hack" said something about unsupported sensor?

**Comment by hypoxic** [comment]
@djbeat2990 can you link me to this "overdrive" hack you are talking about

**Comment by hypoxic** [comment]
@djbeat2990 Check the latest repo. I see what you are calling overdrive from evilwombat. We do something similar for http://turnedon.camera/ to work properly.

**Comment by jonibim** [comment]
sorry my fault... its something else...

**Comment by jonibim** [comment]
but i found this tool http://dc.p-mc.eu/tools/a7tool that modifies ambrella frimware

**Comment by hypoxic** [comment]
Please see the new cal.txt method posted. It's not as strong as autoexec.ash, but will work for most application.
